### ISSUE TITLE
JavaScript client test fails

### ISSUE THREAD

**Issue by penberg** [penberg/hiisi#27]
Steps to reproduce:

```
cd hiisi-server && cargo run
```

```
cd testing/sql/javascript && npm i && node index.js
```

Actual output:

```
[2024-08-12T09:11:35Z INFO  hiisid] Listening for SQL HTTP requests on 127.0.0.1:8080
thread 'main' panicked at hiisi-server/src/server.rs:75:35:
called `Result::unwrap()` on an `Err` value: Token
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by JeanArhancet** [comment]
@penberg I would like to contribute to this task 😄

**Comment by penberg** [comment]
@numinnex The JavaScript client still fails (although with a different error) so I am reopening this:

```
penberg@vonneumann javascript % node index.js
file:///Users/penberg/src/tursodatabase/hiisi/hiisi-server/testing/sql/javascript/node_modules/@libsql/client/lib-esm/hrana.js:262
        return new LibsqlError(e.message, code, undefined, e);
               ^

LibsqlError: SERVER_ERROR: Server returned HTTP status 500: Parse error: invalid type: integer `77`, expected struct PipelineReqBody at line 1 column 2
    at mapHranaError (file:///Users/penberg/src/tursodatabase/hiisi/hiisi-server/testing/sql/javascript/node_modules/@libsql/client/lib-esm/hrana.js:262:16)
    at file:///Users/penberg/src/tursodatabase/hiisi/hiisi-server/testing/sql/javascript/node_modules/@libsql/client/lib-esm/http.js:76:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/penberg/src/tursodatabase/hiisi/hiisi-server/testing/sql/javascript/index.js:7:1 {
  code: 'SERVER_ERROR',
  rawCode: undefined,
  [cause]: HttpServerError: Server returned HTTP status 500: Parse error: invalid type: integer `77`, expected struct PipelineReqBody at line 1 column 2
      at errorFromResponse (file:///Users/penberg/src/tursodatabase/hiisi/hiisi-server/testing/sql/javascript/node_modules/@libsql/hrana-client/lib-esm/http/stream.js:360:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    status: 500
  }
}

```
